# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='Sport', on_delete=django.db.models.deletion.PROTECT, to='events.EventCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
