# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170613_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Tallinn', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='59.43696079999999,24.75357459999998', max_length=63),
        ),
    ]
