# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170614_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Tallinn', max_length=255, verbose_name='Linn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripton',
            field=models.TextField(verbose_name='Projekti sisu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Algus kuupäev ja kellaaeg'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='59.43696079999999,24.75357459999998', max_length=63, verbose_name='Asukoht'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_limit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Lõppemis kuupäev'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Projekti nimi'),
        ),
    ]
