# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170616_1251'),
        ('events', '0004_auto_20170619_1053'),
    ]

    operations = [
    ]
