# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170608_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='field',
            new_name='category',
        ),
    ]
