# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170609_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategories',
            new_name='EventCategory',
        ),
    ]
