# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170609_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('Määramata'), to='events.EventCategory'),
        ),
    ]
